server:
  port: 0

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/core/main-service/{application}
            - classpath:config/stats-service/stats-server/{application}
            - classpath:config/infra/gateway/{application}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info